### ISSUE TITLE
Failed to execute. Invalid field type

### ISSUE THREAD

**Issue by mayja02** [crackernutter/EsriRESTScraper#7]
createFeatureClass() failing to execute on example REST service in README as well as a couple other services I tested.

This is the error I am getting when running from IDLE.
```
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    data = dataScraper.createFeatureClass("C:\Users\...\Documents\ArcGIS\Default.gdb", "WMADATA")
  File "C:\Python27\ArcGIS10.3\lib\site-packages\RestCacheClass.py", line 167, in createFeatureClass
    self.__createFields()
  File "C:\Python27\ArcGIS10.3\lib\site-packages\RestCacheClass.py", line 174, in __createFields
    self.__createField(field)
  File "C:\Python27\ArcGIS10.3\lib\site-packages\RestCacheClass.py", line 200, in __createField
    arcpy.AddField_management(in_table=featureClass, field_name=name, field_type=fieldType, field_length=fieldLength)
  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcPy\arcpy\management.py", line 3246, in AddField
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000800: The value is not a member of TEXT | FLOAT | DOUBLE | SHORT | LONG | DATE | BLOB | RASTER | GUID.
Failed to execute (AddField).
```

This is my first issue submitted so forgive me if I miss any expected etiquette.  This is a cool project.

**Comment by crackernutter** [comment]
what is the REST endpoint you're trying to get?  It may have an unsupported field type.

**Comment by crackernutter** [comment]
No response

**Comment by crackernutter** [comment]
No response - closing issue
